/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.kilamea

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val valueUnderTest = "Hello"
        assertNotNull(valueUnderTest, "value should not be null")
    }
}
